[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-kaos.json"

[target.x86_64-kaos]
rustflags = [
    "-C", "link-arg=-Tlink.ld",

    "-C", "opt-level=1",
    "-C", "force-frame-pointers=yes",
    "-C", "debuginfo=2",
    "-C", "codegen-units=1"
]